"""Where this process itself is reachable — the one thing a request can't tell you.

The backend's port is resolved at startup (fixed via CURRY_LEAVES_PORT, or a random
free port picked by app.py) and only known inside app.py after that point. Anything
that needs to hand out an absolute, externally-reachable URL — e.g. an artifact's
public share link, generated by a tool call with no Request object in hand — reads it
from here instead of re-deriving it.
"""
from __future__ import annotations

_base_url: str | None = None


def set_base_url(host: str, port: int) -> None:
    global _base_url
    # 0.0.0.0 (bind-all) isn't a URL a client can use; loopback is the honest default
    # for a link the user will open from the same machine.
    public_host = "127.0.0.1" if host in ("0.0.0.0", "::") else host
    _base_url = f"http://{public_host}:{port}"


def base_url() -> str:
    return _base_url or "http://127.0.0.1"
